name: 'AWS SSM'
description: 'Lookup AWS parameter store value'
inputs:
  key:
    description: 'parameter store key'
    required: true
outputs:
  value:
    description: 'parameter store value'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.key }}
